disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - implicitly_unwrapped_optional
  - redundant_nil_coalescing
  - fatal_error_message
  - closure_spacing
  - sorted_imports
  - unused_optional_binding
  - unused_closure_parameter
  - vertical_parameter_alignment
  - closure_end_indentation
  - explicit_init
  - first_where
  - number_separator
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - strict_fileprivate
  - switch_case_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_string
  - flatmap_over_map_reduce
  - last_where
  - reduce_into
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - weak_delegate

excluded:
  - Pods
  - DerivedData
  - .build
  - fastlane
  - vendor
  - Cards/GeneratedMocks.swift

force_cast: warning
force_try: warning

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - x
    - y
    - i
    - j
    - to
    - at
    - in
    - me
    - or
    - on
    - up
    - if
    - ok
    - db
    - vm
    - vc
    - ui
    - ip
    - qa
    - tv
    - os
    - no
    - by
    - is
    - am
    - pm
    - of
    - as
    - it
    - vs
    - we
    - us
    - my
    - he
    - do
    - be
    - go
    - so
    - an
    - a
    - r
    - s
    - t
    - v
    - w
    - z
    - _

reporter: xcode

