name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - 'docs/**'
      - '.gitignore'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'Website/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - 'docs/**'
      - '.gitignore'
      - 'Gemfile'
      - 'Website/**'
      - 'Gemfile.lock'

jobs:
  build-and-test:
    runs-on: macos-26
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: List available simulators
      run: xcrun simctl list devices available | grep "iPhone 17 Pro Max"
    
    - name: Build and Test
      run: |
        xcodebuild -scheme Cards \
          -destination 'platform=iOS Simulator,name=iPhone 17 Pro Max,OS=26.1,arch=arm64' \
          -skipPackagePluginValidation \
          clean build test -quiet
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
