name: Deploy to TestFlight

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: macos-26
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Fastlane
      run: brew install fastlane
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
    
    - name: Deploy to TestFlight
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      run: fastlane beta
